# Favicon
favicon: '/logo/favicon.ico'

# --------------------
# Navbar
# --------------------
navbar:
  # The URL of Logo which will be shown at navbar
  logo: '/logo/navbar.png'
  # If you Logo has no text, you can add title next to your logo.
  # Leave it as an empty string if you don't have
  logo_text: ''
  links:
    zh-CN:
      # - logo: # The font-awesome class name of the logo. Leave it blank if you don't need logo for this link
      #  text: '使用文档' # The logo text
      #  url: '/' # The url
      - logo: 'fab fa-github' # The font-awesome class name of the logo
        text: 'GitHub' # The logo text
        url: 'https://github.com/SukkaW/OpenCore-Document-zh_Hans' # The url

# --------------------
# Sidebar Items
# --------------------
sidebar:
  zh-CN: # Language
    docs: # Type bname
      level: 1 # 1 or 2
      items:
        - 0. 首页 | index.html
        - 1. 简介 | 1-introduction.html
        - 2. 配置 | 2-configuration.html
        - 3. Setup | 3-setup.html
        - 4. ACPI | 4-acpi.html
        - 5. Booter | 5-booter.html
        - 6. DeviceProperties | 6-device-properties.html
        - 7. Kernel | 7-kernel.html
        - 8. Misc | 8-misc.html
        - 9. NVRAM | 9-nvram.html
        - 10. PlatformInfo | 10-platform-info.html
        - 11. UEFI | 11-uefi.html
        - 12. 排错 | 12-troubleshooting.html

github:
  repo: sukkaw/OpenCore-Document-zh_Hans # sukkaw/doku-theme-docs
  edit_on_github: true # true / false
